-- 插入generic类型的角色数据
-- 基于权威数据和文件，使用GitHub仓库URL

INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-australia-man-average-height', 'Australia Man Average Height', 1.788, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Australia%20man%20average%20height-1.788.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Australia%20man%20average%20height-1.788.png', NULL, false, NULL, 800),
('generic-brazilian-man-average-height', 'Brazilian Man Average Height', 1.757, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/brazilian%20man%20average%20height-1.757.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/brazilian%20man%20average%20height-1.757.png', NULL, false, NULL, 800),
('generic-canada-man-average-height', 'Canada Man Average Height', 1.788, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Canada%20man%20average%20height-1.788.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Canada%20man%20average%20height-1.788.png', NULL, false, NULL, 800),
('generic-china-man-average-height', 'China Man Average Height', 1.757, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/China%20man%20average%20height-1.757.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/China%20man%20average%20height-1.757.png', NULL, false, NULL, 800),
('generic-denmark-man-average-height', 'Denmark Man Average Height', 1.8189, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Denmark%20man%20average%20height-1.8189.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Denmark%20man%20average%20height-1.8189.png', NULL, false, NULL, 800),
('generic-france-man-average-height', 'France Man Average Height', 1.797, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/France%20man%20average%20height-1.797.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/France%20man%20average%20height-1.797.png', NULL, false, NULL, 800),
('generic-germany-man-average-height', 'Germany Man Average Height', 1.808, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Germany%20man%20average%20height-1.808.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Germany%20man%20average%20height-1.808.png', NULL, false, NULL, 800),
('generic-iceland-male-average-height', 'Iceland Male Average Height', 1.821, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Iceland%20male%20average%20height-1.821.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Iceland%20male%20average%20height-1.821.png', NULL, false, NULL, 800),
('generic-indian-man-average-height', 'Indian Man Average Height', 1.665, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Indian%20man%20average%20height-1.665.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Indian%20man%20average%20height-1.665.png', NULL, false, NULL, 800),
('generic-indonesian-man-average-height', 'Indonesian Man Average Height', 1.663, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/indonesian%20man%20average%20height-1.663.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/indonesian%20man%20average%20height-1.663.png', NULL, false, NULL, 800),
('generic-japanese-man-average-height', 'Japanese Man Average Height', 1.721, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Japanese%20man%20average%20height-1.721.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Japanese%20man%20average%20height-1.721.png', NULL, false, NULL, 800),
('generic-mexican-man-average-height', 'Mexican Man Average Height', 1.703, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Mexican%20man%20average%20height-1.703.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Mexican%20man%20average%20height-1.703.png', NULL, false, NULL, 800),
('generic-netherlands-man-average-height', 'Netherlands Man Average Height', 1.8378, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Netherlands%20man%20average%20height-1.8378.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Netherlands%20man%20average%20height-1.8378.png', NULL, false, NULL, 800),
('generic-philippines-man-average-height', 'Philippines Man Average Height', 1.633, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Philippines%20man%20average%20height-1.633.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Philippines%20man%20average%20height-1.633.png', NULL, false, NULL, 800),
('generic-south-korea-man-average-height', 'South Korea Man Average Height', 1.755, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/South%20Korea%20man%20average%20height-1.755.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/South%20Korea%20man%20average%20height-1.755.png', NULL, false, NULL, 800),
('generic-ukraine-man-average-height', 'Ukraine Man Average Height', 1.8098, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Ukraine%20man%20average%20height-1.8098.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Ukraine%20man%20average%20height-1.8098.png', NULL, false, NULL, 800),
('generic-united-kingdom', 'United Kingdom', 1.782, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/United%20Kingdom-1.782.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/United%20Kingdom-1.782.png', NULL, false, NULL, 800),
('generic-united-states-man-average-height', 'United States Man Average Height', 1.769, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/United%20States%20man%20average%20height-1.769.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/United%20States%20man%20average%20height-1.769.png', NULL, false, NULL, 800),
('generic-vietnam-man-average-height', 'Vietnam Man Average Height', 1.684, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Vietnam%20man%20average%20height-1.684.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Vietnam%20man%20average%20height-1.684.png', NULL, false, NULL, 800);
