-- 插入object类型的角色数据
-- 基于权威数据和文件，使用GitHub仓库URL

INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('object-jupiter', 'Jupiter', 139822000, 'object', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/Jupiter-139822000.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/Jupiter-139822000.png', NULL, false, NULL, 2100),
('object-mars', 'Mars', 6779000, 'object', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/mars-6779000.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/mars-6779000.png', NULL, false, NULL, 2100),
('object-mercury', 'Mercury', 4880000, 'object', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/Mercury-4880000.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/Mercury-4880000.png', NULL, false, NULL, 2100),
('object-neptune', 'Neptune', 49244000, 'object', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/neptune-49244000.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/neptune-49244000.png', NULL, false, NULL, 2100),
('object-saturn', 'Saturn', 116464000, 'object', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/Saturn-116464000.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/Saturn-116464000.png', NULL, false, NULL, 2100),
('object-uranus', 'Uranus', 50724000, 'object', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/Uranus-50724000.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/Uranus-50724000.png', NULL, false, NULL, 2100),
('object-venus', 'Venus', 12104000, 'object', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/Venus-12104000.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/object/Venus-12104000.png', NULL, false, NULL, 2100);
