-- 插入microorganisms类型的角色数据
-- 基于权威数据和文件，使用GitHub仓库URL

INSERT INTO public.characters (id, name, height, cat_ids, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('microorganisms-bacteria_prokaryotic_cell', 'Bacteria Prokaryotic Cell', 0.000001, ARRAY[0,8], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/microorganisms/Bacteria%20prokaryotic%20cell-0.000001.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/microorganisms/Bacteria%20prokaryotic%20cell-0.000001.png', NULL, false, NULL, 8000),
('microorganisms-eukaryotic_cell_human_cell', 'Eukaryotic Cell Human Cell', 0.000015, ARRAY[0,8], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/microorganisms/Eukaryotic%20cell%20human%20cell-0.000015.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/microorganisms/Eukaryotic%20cell%20human%20cell-0.000015.png', NULL, false, NULL, 8000),
('microorganisms-mold_mould', 'Mold Mould', 0.000025, ARRAY[0,8], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/microorganisms/Mold%20Mould-0.000025.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/microorganisms/Mold%20Mould-0.000025.png', NULL, false, NULL, 8000),
('microorganisms-virus', 'Virus', 0.0000001, ARRAY[0,8], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/microorganisms/Virus-0.0000001.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/microorganisms/Virus-0.0000001.png', NULL, false, NULL, 8000),
('microorganisms-yeast', 'Yeast', 0.000006, ARRAY[0,8], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/microorganisms/Yeast-0.000006.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/microorganisms/Yeast-0.000006.png', NULL, false, NULL, 8000);
