-- 插入generic类型的角色数据
-- 基于权威身高数据和SVG文件，使用GitHub仓库URL
-- 所有ID统一加上generic-前缀
-- gen开头的角色可自定义颜色并分配清爽随机色彩

-- 清空现有generic角色数据（可选）
-- DELETE FROM characters WHERE type = 'generic';

-- 中性角色 (平均身高1.75米) - 不可自定义颜色
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property,order_num) VALUES
('generic-agender-1', 'Agender 1', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/agender-1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/agender-1.svg', NULL, false, NULL,4),
('generic-agender-2', 'Agender 2', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/agender-2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/agender-2.svg', NULL, false, NULL,4),
('generic-agender-3', 'Agender 3', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/agender-3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/agender-3.svg', NULL, false, NULL,4),
('generic-agender-4', 'Agender 4', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/agender-4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/agender-4.svg', NULL, false, NULL,700),
('generic-agender-5', 'Agender 5', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/agender-5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/agender-5.svg', NULL, false, NULL,701),
('generic-agender-6', 'Agender 6', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/agender-6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/agender-6.svg', NULL, false, NULL,702);


-- 1岁婴儿角色 (平均身高0.75米) - 不可自定义颜色
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-baby-1', 'Baby 1', 0.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/baby1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/baby1.svg', '#3B82F6', true, 'fill', 4),
('generic-baby-2', 'Baby 2', 0.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/baby2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/baby2.svg', '#10B981', true, 'fill', 4),
('generic-baby-3', 'Baby 3', 0.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/baby3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/baby3.svg', NULL, false, NULL, 300),
('generic-baby-4', 'Baby 4', 0.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/baby4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/baby4.svg', NULL, false, NULL, 300),
('generic-baby-5', 'Baby 5', 0.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/baby5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/baby5.svg', NULL, false, NULL, 300);


-- 5岁男孩角色 (平均身高1.10米) - 不可自定义颜色
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-child-kid-5years-boy-1', '5years Child Boy 1', 1.10, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-boy1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-boy1.svg', NULL, false, NULL, 330),
('generic-child-kid-5years-boy-2', '5years Child Boy 2', 1.10, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-boy2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-boy2.svg', NULL, false, NULL, 330),
('generic-child-kid-5years-boy-3', '5years Child Boy 3', 1.10, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-boy3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-boy3.svg', NULL, false, NULL, 330),
('generic-child-kid-5years-boy-4', '5years Child Boy 4', 1.10, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-boy4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-boy4.svg', NULL, false, NULL, 330),
('generic-child-kid-5years-boy-5', '5years Child Boy 5', 1.10, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-boy5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-boy5.svg', NULL, false, NULL, 330),
('generic-child-kid-5years-boy-6', '5years Child Boy 6', 1.10, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-boy6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-boy6.svg', NULL, false, NULL, 330);

-- 5岁女孩角色 (平均身高1.10米) - 不可自定义颜色
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-child-kid-5years-girl-1', '5years Child Girl 1', 1.10, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-girl1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-girl1.svg', NULL, false, NULL, 330),
('generic-child-kid-5years-girl-2', '5years Child Girl 2', 1.10, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-girl2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-girl2.svg', NULL, false, NULL, 330),
('generic-child-kid-5years-girl-3', '5years Child Girl 3', 1.10, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-girl3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-girl3.svg', NULL, false, NULL, 330),
('generic-child-kid-5years-girl-4', '5years Child Girl 4', 1.10, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-girl4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-girl4.svg', NULL, false, NULL, 330),
('generic-child-kid-5years-girl-5', '5years Child Girl 5', 1.10, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-girl5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-girl5.svg', NULL, false, NULL, 330),
('generic-child-kid-5years-girl-6', '5years Child Girl 6', 1.10, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-girl6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-5years-girl6.svg', NULL, false, NULL, 330);


-- 12岁男孩角色 (平均身高1.52米) - 不可自定义颜色
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-child-kid-12years-boy-1', '12years Child Boy 1', 1.52, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-boy1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-boy1.svg', NULL, false, NULL, 310),
('generic-child-kid-12years-boy-2', '12years Child Boy 2', 1.52, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-boy2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-boy2.svg', NULL, false, NULL, 310),
('generic-child-kid-12years-boy-3', '12years Child Boy 3', 1.52, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-boy3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-boy3.svg', NULL, false, NULL, 310),
('generic-child-kid-12years-boy-4', '12years Child Boy 4', 1.52, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-boy4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-boy4.svg', NULL, false, NULL, 310);

-- 12岁女孩角色 (平均身高1.45米) - 不可自定义颜色
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-child-kid-12years-girl-1', '12years Child Girl 1', 1.45, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-girl1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-girl1.svg', NULL, false, NULL, 320),
('generic-child-kid-12years-girl-2', '12years Child Girl 2', 1.45, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-girl2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-girl2.svg', NULL, false, NULL, 320),
('generic-child-kid-12years-girl-3', '12years Child Girl 3', 1.45, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-girl3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-girl3.svg', NULL, false, NULL, 320),
('generic-child-kid-12years-girl-4', '12years Child Girl 4', 1.45, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-girl4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/child-kid-12years-girl4.svg', NULL, false, NULL, 320);


-- 成年男性角色 (平均身高1.75米) - 不可自定义颜色
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-man-1', 'Man 1', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man1.svg', NULL, false, NULL, 2),
('generic-man-2', 'Man 2', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man2.svg', NULL, false, NULL, 2),
('generic-man-3', 'Man 3', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man3.svg', NULL, false, NULL, 2),
('generic-man-4', 'Man 4', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man4.svg', NULL, false, NULL, 103),
('generic-man-5', 'Man 5', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man5.svg', NULL, false, NULL, 104),
('generic-man-6', 'Man 6', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man6.svg', NULL, false, NULL, 105),
('generic-man-7', 'Man 7', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man7.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man7.svg', NULL, false, NULL, 106),
('generic-man-8', 'Man 8', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man8.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man8.svg', NULL, false, NULL, 107);

-- 成年女性角色 (平均身高1.62米) - 不可自定义颜色
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-woman-1', 'Woman 1', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman1.svg', NULL, false, NULL, 3),
('generic-woman-2', 'Woman 2', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman2.svg', NULL, false, NULL, 3),
('generic-woman-3', 'Woman 3', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman3.svg', NULL, false, NULL, 3),
('generic-woman-4', 'Woman 4', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman4.svg', NULL, false, NULL, 203),
('generic-woman-5', 'Woman 5', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman5.svg', NULL, false, NULL, 204),
('generic-woman-6', 'Woman 6', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman6.svg', NULL, false, NULL, 205),
('generic-woman-7', 'Woman 7', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman7.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman7.svg', NULL, false, NULL, 206);


-- 16岁男孩角色 (平均身高1.65米) - 不可自定义颜色
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-teenager-16years-boy-1', '16years Teenager Boy 1', 1.65, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy1.svg', NULL, false, NULL, 340),
('generic-teenager-16years-boy-2', '16years Teenager Boy 2', 1.65, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy2.svg', NULL, false, NULL, 340),
('generic-teenager-16years-boy-3', '16years Teenager Boy 3', 1.65, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy3.svg', NULL, false, NULL, 340),
('generic-teenager-16years-boy-4', '16years Teenager Boy 4', 1.65, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy4.svg', NULL, false, NULL, 340),
('generic-teenager-16years-boy-5', '16years Teenager Boy 5', 1.65, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy5.svg', NULL, false, NULL, 340),
('generic-teenager-16years-boy-6', '16years Teenager Boy 6', 1.65, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy6.svg', NULL, false, NULL, 340),
('generic-teenager-16years-boy-7', '16years Teenager Boy 7', 1.65, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy7.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy7.svg', NULL, false, NULL, 340),
('generic-teenager-16years-boy-8', '16years Teenager Boy 8', 1.65, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy8.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-boy8.svg', NULL, false, NULL, 340);

-- 16岁女孩角色 (平均身高1.55米) - 不可自定义颜色
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-teenager-16years-girl-1', '16years Teenager Girl 1', 1.55, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl1.svg', NULL, false, NULL, 350),
('generic-teenager-16years-girl-2', '16years Teenager Girl 2', 1.55, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl2.svg', NULL, false, NULL, 350),
('generic-teenager-16years-girl-3', '16years Teenager Girl 3', 1.55, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl3.svg', NULL, false, NULL, 350),
('generic-teenager-16years-girl-4', '16years Teenager Girl 4', 1.55, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl4.svg', NULL, false, NULL, 350),
('generic-teenager-16years-girl-5', '16years Teenager Girl 5', 1.55, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl5.svg', NULL, false, NULL, 350),
('generic-teenager-16years-girl-6', '16years Teenager Girl 6', 1.55, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl6.svg', NULL, false, NULL, 350),
('generic-teenager-16years-girl-7', '16years Teenager Girl 7', 1.55, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl7.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl7.svg', NULL, false, NULL, 350),
('generic-teenager-16years-girl-8', '16years Teenager Girl 8', 1.55, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl8.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/teenager-16years-girl8.svg', NULL, false, NULL, 350);


-- 老年男性角色 (平均身高1.68米) - 不可自定义颜色
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-oldman-1', 'Old Man 1', 1.68, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman1.svg', NULL, false, NULL, 500),
('generic-oldman-2', 'Old Man 2', 1.68, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman2.svg', NULL, false, NULL, 501),
('generic-oldman-3', 'Old Man 3', 1.68, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman3.svg', NULL, false, NULL, 502),
('generic-oldman-4', 'Old Man 4', 1.68, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman4.svg', NULL, false, NULL, 503),
('generic-oldman-5', 'Old Man 5', 1.68, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman5.svg', NULL, false, NULL, 504);

-- 老年女性角色 (平均身高1.58米) - 不可自定义颜色
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-oldwoman-1', 'Old Woman 1', 1.58, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman1.svg', NULL, false, NULL, 600),
('generic-oldwoman-2', 'Old Woman 2', 1.58, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman2.svg', NULL, false, NULL, 601),
('generic-oldwoman-3', 'Old Woman 3', 1.58, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman3.svg', NULL, false, NULL, 602),
('generic-oldwoman-4', 'Old Woman 4', 1.58, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman4.svg', NULL, false, NULL, 603),
('generic-oldwoman-5', 'Old Woman 5', 1.58, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman5.svg', NULL, false, NULL, 604),
('generic-oldwoman-6', 'Old Woman 6', 1.58, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman6.svg', NULL, false, NULL, 605);

-- 可自定义颜色的成年男性角色 (genman系列) - 清爽随机色彩
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-genman-1', 'Generic Man 1', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman1.svg', '#3B82F6', true, 'fill', 10),
('generic-genman-2', 'Generic Man 2', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman2.svg', '#10B981', true, 'fill', 11),
('generic-genman-3', 'Generic Man 3', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman3.svg', '#F59E0B', true, 'fill', 12),
('generic-genman-4', 'Generic Man 4', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman4.svg', '#8B5CF6', true, 'fill', 13),
('generic-genman-5', 'Generic Man 5', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman5.svg', '#EF4444', true, 'fill', 14),
('generic-genman-6', 'Generic Man 6', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman6.svg', '#06B6D4', true, 'fill', 0),
('generic-genman-7', 'Generic Man 7', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman7.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman7.svg', '#84CC16', true, 'fill', 0),
('generic-genman-8', 'Generic Man 8', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman8.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman8.svg', '#F97316', true, 'fill', 0);

-- 可自定义颜色的成年女性角色 (genwoman系列) - 清爽随机色彩
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-genwoman-1', 'Generic Woman 1', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman1.svg', '#EC4899', true, 'fill', 50),
('generic-genwoman-2', 'Generic Woman 2', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman2.svg', '#14B8A6', true, 'fill', 51),
('generic-genwoman-3', 'Generic Woman 3', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman3.svg', '#A855F7', true, 'fill', 52),
('generic-genwoman-4', 'Generic Woman 4', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman4.svg', '#22C55E', true, 'fill', 53),
('generic-genwoman-5', 'Generic Woman 5', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman5.svg', '#3B82F6', true, 'fill', 54),
('generic-genwoman-6', 'Generic Woman 6', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman6.svg', '#F59E0B', true, 'fill', 1),
('generic-genwoman-7', 'Generic Woman 7', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman7.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman7.svg', '#EF4444', true, 'fill', 1),
('generic-genwoman-8', 'Generic Woman 8', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman8.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman8.svg', '#06B6D4', true, 'fill', 1);

-- 主要国家男性平均身高
INSERT INTO public.characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('generic-australia-man-average-height', 'Australia Man Average Height', 1.788, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Australia%20man%20average%20height-1.788.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Australia%20man%20average%20height-1.788.png', NULL, false, NULL, 800),
('generic-brazilian-man-average-height', 'Brazilian Man Average Height', 1.757, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/brazilian%20man%20average%20height-1.757.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/brazilian%20man%20average%20height-1.757.png', NULL, false, NULL, 800),
('generic-canada-man-average-height', 'Canada Man Average Height', 1.788, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Canada%20man%20average%20height-1.788.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Canada%20man%20average%20height-1.788.png', NULL, false, NULL, 800),
('generic-china-man-average-height', 'China Man Average Height', 1.757, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/China%20man%20average%20height-1.757.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/China%20man%20average%20height-1.757.png', NULL, false, NULL, 800),
('generic-denmark-man-average-height', 'Denmark Man Average Height', 1.8189, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Denmark%20man%20average%20height-1.8189.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Denmark%20man%20average%20height-1.8189.png', NULL, false, NULL, 800),
('generic-france-man-average-height', 'France Man Average Height', 1.797, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/France%20man%20average%20height-1.797.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/France%20man%20average%20height-1.797.png', NULL, false, NULL, 800),
('generic-germany-man-average-height', 'Germany Man Average Height', 1.808, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Germany%20man%20average%20height-1.808.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Germany%20man%20average%20height-1.808.png', NULL, false, NULL, 800),
('generic-iceland-male-average-height', 'Iceland Male Average Height', 1.821, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Iceland%20male%20average%20height-1.821.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Iceland%20male%20average%20height-1.821.png', NULL, false, NULL, 800),
('generic-indian-man-average-height', 'Indian Man Average Height', 1.665, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Indian%20man%20average%20height-1.665.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Indian%20man%20average%20height-1.665.png', NULL, false, NULL, 800),
('generic-indonesian-man-average-height', 'Indonesian Man Average Height', 1.663, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/indonesian%20man%20average%20height-1.663.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/indonesian%20man%20average%20height-1.663.png', NULL, false, NULL, 800),
('generic-japanese-man-average-height', 'Japanese Man Average Height', 1.721, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Japanese%20man%20average%20height-1.721.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Japanese%20man%20average%20height-1.721.png', NULL, false, NULL, 800),
('generic-mexican-man-average-height', 'Mexican Man Average Height', 1.703, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Mexican%20man%20average%20height-1.703.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Mexican%20man%20average%20height-1.703.png', NULL, false, NULL, 800),
('generic-netherlands-man-average-height', 'Netherlands Man Average Height', 1.8378, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Netherlands%20man%20average%20height-1.8378.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Netherlands%20man%20average%20height-1.8378.png', NULL, false, NULL, 800),
('generic-philippines-man-average-height', 'Philippines Man Average Height', 1.633, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Philippines%20man%20average%20height-1.633.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Philippines%20man%20average%20height-1.633.png', NULL, false, NULL, 800),
('generic-south-korea-man-average-height', 'South Korea Man Average Height', 1.755, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/South%20Korea%20man%20average%20height-1.755.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/South%20Korea%20man%20average%20height-1.755.png', NULL, false, NULL, 800),
('generic-ukraine-man-average-height', 'Ukraine Man Average Height', 1.8098, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Ukraine%20man%20average%20height-1.8098.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Ukraine%20man%20average%20height-1.8098.png', NULL, false, NULL, 800),
('generic-united-kingdom', 'United Kingdom', 1.782, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/United%20Kingdom-1.782.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/United%20Kingdom-1.782.png', NULL, false, NULL, 800),
('generic-united-states-man-average-height', 'United States Man Average Height', 1.769, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/United%20States%20man%20average%20height-1.769.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/United%20States%20man%20average%20height-1.769.png', NULL, false, NULL, 800),
('generic-vietnam-man-average-height', 'Vietnam Man Average Height', 1.684, 'generic', 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Vietnam%20man%20average%20height-1.684.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/Vietnam%20man%20average%20height-1.684.png', NULL, false, NULL, 800);

-- 检查插入结果
SELECT 
    type, 
    color_customizable,
    COUNT(*) as count,
    AVG(height) as avg_height,
    MIN(height) as min_height,
    MAX(height) as max_height
FROM characters 
WHERE type = 'generic'
GROUP BY type, color_customizable
ORDER BY color_customizable;

-- 显示所有generic角色概览
SELECT id, name, height, color, color_customizable, "order" FROM characters WHERE type = 'generic' ORDER BY "order", name;