-- 插入fictional_characters类型的角色数据
-- 基于权威数据和文件，使用GitHub仓库URL

INSERT INTO public.characters (id, name, height, cat_ids, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('fictional_characters-godzilla_2021', 'Godzilla 2021', 119.8, ARRAY[0,4], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/fictional_characters/Godzilla%202021-119.8.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/fictional_characters/Godzilla%202021-119.8.png', NULL, false, NULL, 4000),
('fictional_characters-harry_potter', 'Harry Potter', 1.83, ARRAY[0,4], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/fictional_characters/Harry%20Potter-1.83.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/fictional_characters/Harry%20Potter-1.83.png', NULL, false, NULL, 4000),
('fictional_characters-hobbits', 'Hobbits', 1, ARRAY[0,4], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/fictional_characters/Hobbits-1.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/fictional_characters/Hobbits-1.png', NULL, false, NULL, 4000),
('fictional_characters-iron_man', 'Iron Man', 1.98, ARRAY[0,4], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/fictional_characters/Iron%20Man-1.98.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/fictional_characters/Iron%20Man-1.98.png', NULL, false, NULL, 4000),
('fictional_characters-thor', 'Thor', 1.98, ARRAY[0,4], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/fictional_characters/Thor-1.98.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/fictional_characters/Thor-1.98.png', NULL, false, NULL, 4000);
