-- 插入plants类型的角色数据
-- 基于权威数据和文件，使用GitHub仓库URL

INSERT INTO public.characters (id, name, height, cat_ids, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('plants-bamboo', 'Bamboo', 30, ARRAY[0,7], 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Bamboo-30.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Bamboo-30.svg', NULL, false, NULL, 7000),
('plants-grass', 'Grass', 0.1, ARRAY[0,7], 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Grass-0.1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Grass-0.1.svg', NULL, false, NULL, 7000),
('plants-pine_tree', 'Pine Tree', 20, ARRAY[0,7], 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Pine%20Tree-20.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Pine%20Tree-20.svg', NULL, false, NULL, 7000),
('plants-poplar_tree', 'Poplar Tree', 25, ARRAY[0,7], 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Poplar%20Tree-25.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Poplar%20Tree-25.svg', NULL, false, NULL, 7000),
('plants-rose', 'Rose', 1, ARRAY[0,7], 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Rose-1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Rose-1.svg', NULL, false, NULL, 7000),
('plants-sunflower', 'Sunflower', 3, ARRAY[0,7], 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Sunflower-3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Sunflower-3.svg', NULL, false, NULL, 7000),
('plants-willow_tree', 'Willow Tree', 15, ARRAY[0,7], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Willow%20Tree-15.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters_v2/refs/heads/main/plants/Willow%20Tree-15.png', NULL, false, NULL, 7000);
