-- 插入objects类型的角色数据
-- 基于权威数据和文件，使用GitHub仓库URL

INSERT INTO public.characters (id, name, height, cat_ids, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('objects-astronomy-2004_fh', '2004 Fh', 30, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/2004_FH-30.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/2004_FH-30.png', NULL, false, NULL, 9000),
('objects-astronomy-2008_tc3', '2008 Tc3', 4.1, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/2008_TC3-4.1.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/2008_TC3-4.1.png', NULL, false, NULL, 9000),
('objects-astronomy-2014_rc', '2014 Rc', 22, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/2014_RC-22.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/2014_RC-22.png', NULL, false, NULL, 9000),
('objects-astronomy-243_ida', '243 Ida', 31400, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/243_Ida-31400.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/243_Ida-31400.png', NULL, false, NULL, 9000),
('objects-astronomy-29075_1950_da', '29075 1950 Da', 1100, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/29075_1950_DA-1100.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/29075_1950_DA-1100.png', NULL, false, NULL, 9000),
('objects-astronomy-3200_phaethon', '3200 Phaethon', 5800, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/3200_Phaethon-5800.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/3200_Phaethon-5800.png', NULL, false, NULL, 9000),
('objects-astronomy-323_brucia', '323 Brucia', 33000, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/323_Brucia-33000.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/323_Brucia-33000.png', NULL, false, NULL, 9000),
('objects-astronomy-433_eros', '433 Eros', 16840, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/433_Eros-16840.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/433_Eros-16840.png', NULL, false, NULL, 9000),
('objects-astronomy-4769_castalia', '4769 Castalia', 1400, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/4769_Castalia-1400.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/4769_Castalia-1400.png', NULL, false, NULL, 9000),
('objects-astronomy-52_europa', '52 Europa', 315000, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/52_Europa-315000.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/52_Europa-315000.png', NULL, false, NULL, 9000),
('objects-astronomy-5_astraea', '5 Astraea', 119000, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/5_Astraea-119000.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/5_Astraea-119000.png', NULL, false, NULL, 9000),
('objects-astronomy-69230_hermes', '69230 Hermes', 810, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/69230_Hermes-810.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/69230_Hermes-810.png', NULL, false, NULL, 9000),
('objects-astronomy-719_albert', '719 Albert', 2360, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/719_Albert-2360.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/719_Albert-2360.png', NULL, false, NULL, 9000),
('objects-astronomy-99942_apophis', '99942 Apophis', 370, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/99942_Apophis-370.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/99942_Apophis-370.png', NULL, false, NULL, 9000),
('objects-astronomy-ceres', 'Ceres', 939000, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/Ceres-939000.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/Ceres-939000.png', NULL, false, NULL, 9000),
('objects-astronomy-eugenia', 'Eugenia', 214000, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/Eugenia-214000.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/Eugenia-214000.png', NULL, false, NULL, 9000),
('objects-astronomy-vesta', 'Vesta', 525000, ARRAY[0,9,910], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/Vesta-525000.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/objects/astronomy/Vesta-525000.png', NULL, false, NULL, 9000);
