-- 插入animals类型的角色数据
-- 基于权威数据和文件，使用GitHub仓库URL

INSERT INTO public.characters (id, name, height, cat_ids, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('animals-beetle', 'Beetle', 0.03, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/beetle-0.03.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/beetle-0.03.png', NULL, false, NULL, 6000),
('animals-big_ant_length', 'Big Ant Length', 0.03, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/big_ant_length-0.03.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/big_ant_length-0.03.png', NULL, false, NULL, 6000),
('animals-blue_whale_length', 'Blue Whale Length', 24, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/blue_whale_length-24.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/blue_whale_length-24.png', NULL, false, NULL, 6000),
('animals-centipedes', 'Centipedes', 0.04, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/centipedes-0.04.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/centipedes-0.04.png', NULL, false, NULL, 6000),
('animals-common_frog', 'Common Frog', 0.08, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/common_frog-0.08.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/common_frog-0.08.png', NULL, false, NULL, 6000),
('animals-dust_mite_length', 'Dust Mite Length', 0.00025, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/dust_mite_length-0.00025.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/dust_mite_length-0.00025.png', NULL, false, NULL, 6000),
('animals-flea_length', 'Flea Length', 0.003, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/flea_length-0.003.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/flea_length-0.003.png', NULL, false, NULL, 6000),
('animals-giant_tortoise', 'Giant Tortoise', 0.8, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/giant_tortoise-0.8.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/giant_tortoise-0.8.png', NULL, false, NULL, 6000),
('animals-gorilla', 'Gorilla', 1.6, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/gorilla-1.6.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/gorilla-1.6.png', NULL, false, NULL, 6000),
('animals-house_fly_length', 'House Fly Length', 0.006, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/house_fly_length-0.006.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/house_fly_length-0.006.png', NULL, false, NULL, 6000),
('animals-japanese_spider_crab_width', 'Japanese Spider Crab Width', 4, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/japanese_spider_crab_width-4.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/japanese_spider_crab_width-4.png', NULL, false, NULL, 6000),
('animals-killer_whale', 'Killer Whale', 7, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/killer_whale-7.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/killer_whale-7.png', NULL, false, NULL, 6000),
('animals-komodo_dragon_length', 'Komodo Dragon Length', 2.6, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/komodo_dragon_length-2.6.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/komodo_dragon_length-2.6.png', NULL, false, NULL, 6000),
('animals-northern_elephant_seal', 'Northern Elephant Seal', 4.5, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/Northern_Elephant_Seal-4.5.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/Northern_Elephant_Seal-4.5.png', NULL, false, NULL, 6000),
('animals-reticulated_python', 'Reticulated Python', 6.25, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/Reticulated_Python-6.25.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/Reticulated_Python-6.25.png', NULL, false, NULL, 6000),
('animals-small_ant_length', 'Small Ant Length', 0.003, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/small_ant_length-0.003.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/small_ant_length-0.003.png', NULL, false, NULL, 6000),
('animals-sperm_whale', 'Sperm Whale', 18, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/sperm_whale-18.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/sperm_whale-18.png', NULL, false, NULL, 6000),
('animals-spider', 'Spider', 0.02, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/spider-0.02.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/spider-0.02.png', NULL, false, NULL, 6000),
('animals-tardigrade_length', 'Tardigrade Length', 0.0005, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/tardigrade_length-0.0005.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/tardigrade_length-0.0005.png', NULL, false, NULL, 6000),
('animals-whale_shark', 'Whale Shark', 10.5, ARRAY[0,6], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/whale_shark-10.5.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/animals/whale_shark-10.5.png', NULL, false, NULL, 6000);
