-- 插入celebrity类型的角色数据
-- 基于权威数据和文件，使用GitHub仓库URL

INSERT INTO public.characters (id, name, height, cat_ids, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('celebrity-ashby_gentry', 'Ashby Gentry', 1.7, ARRAY[0,2,210], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/celebrity/entertainment_celebs/Ashby_Gentry-1.7.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/celebrity/entertainment_celebs/Ashby_Gentry-1.7.png', NULL, false, NULL, 2000),
('celebrity-connor_stanhope', 'Connor Stanhope', 1.83, ARRAY[0,2,210], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/celebrity/entertainment_celebs/Connor_Stanhope-1.83.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/celebrity/entertainment_celebs/Connor_Stanhope-1.83.png', NULL, false, NULL, 2000),
('celebrity-corey_fogelmanis', 'Corey Fogelmanis', 1.77, ARRAY[0,2,210], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/celebrity/entertainment_celebs/Corey_Fogelmanis-1.77.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/celebrity/entertainment_celebs/Corey_Fogelmanis-1.77.png', NULL, false, NULL, 2000),
('celebrity-johnny_link', 'Johnny Link', 1.8, ARRAY[0,2,210], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/celebrity/entertainment_celebs/Johnny_Link-1.8.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/celebrity/entertainment_celebs/Johnny_Link-1.8.png', NULL, false, NULL, 2000),
('celebrity-marc_blucas', 'Marc Blucas', 1.88, ARRAY[0,2,210], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/celebrity/entertainment_celebs/Marc_Blucas-1.88.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/celebrity/entertainment_celebs/Marc_Blucas-1.88.png', NULL, false, NULL, 2000),
('celebrity-sarah_rafferty', 'Sarah Rafferty', 1.76, ARRAY[0,2,210], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/celebrity/entertainment_celebs/Sarah_Rafferty-1.76.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/celebrity/entertainment_celebs/Sarah_Rafferty-1.76.png', NULL, false, NULL, 2000);
