-- 插入films类型的角色数据
-- 基于权威数据和文件，使用GitHub仓库URL

INSERT INTO public.characters (id, name, height, cat_ids, media_type, media_url, thumbnail_url, color, color_customizable, color_property, order_num) VALUES
('films-walking_dead-aaron_twd', 'Aaron Twd', 1.8542, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/aaron_twd-1.8542.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/aaron_twd-1.8542.png', NULL, false, NULL, 10000),
('films-walking_dead-andrea_twd', 'Andrea Twd', 1.65, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/andrea_twd-1.65.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/andrea_twd-1.65.png', NULL, false, NULL, 10000),
('films-walking_dead-beth_greene', 'Beth Greene', 1.65, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/beth_greene-1.65.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/beth_greene-1.65.png', NULL, false, NULL, 10000),
('films-walking_dead-carl_grimes', 'Carl Grimes', 1.7272, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/carl_grimes-1.7272.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/carl_grimes-1.7272.png', NULL, false, NULL, 10000),
('films-walking_dead-carol_peletier', 'Carol Peletier', 1.6764, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/carol_peletier-1.6764.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/carol_peletier-1.6764.png', NULL, false, NULL, 10000),
('films-walking_dead-daryl_dixon', 'Daryl Dixon', 1.765, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/daryl_dixon-1.765.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/daryl_dixon-1.765.png', NULL, false, NULL, 10000),
('films-walking_dead-eugene_porter', 'Eugene Porter', 1.8288, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/eugene_porter-1.8288.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/eugene_porter-1.8288.png', NULL, false, NULL, 10000),
('films-walking_dead-glenn_rhee', 'Glenn Rhee', 1.7272, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/glenn_rhee-1.7272.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/glenn_rhee-1.7272.png', NULL, false, NULL, 10000),
('films-walking_dead-hershel_greene', 'Hershel Greene', 1.8034, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/hershel_greene-1.8034.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/hershel_greene-1.8034.png', NULL, false, NULL, 10000),
('films-walking_dead-maggie_rhee', 'Maggie Rhee', 1.7272, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/maggie_rhee-1.7272.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/maggie_rhee-1.7272.png', NULL, false, NULL, 10000),
('films-walking_dead-merle_dixon', 'Merle Dixon', 1.7526, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/merle_dixon-1.7526.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/merle_dixon-1.7526.png', NULL, false, NULL, 10000),
('films-walking_dead-michonne_hawthorne', 'Michonne Hawthorne', 1.7, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/michonne_hawthorne-1.7.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/michonne_hawthorne-1.7.png', NULL, false, NULL, 10000),
('films-walking_dead-morgan_jones', 'Morgan Jones', 1.778, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/morgan_jones-1.778.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/morgan_jones-1.778.png', NULL, false, NULL, 10000),
('films-walking_dead-negan_smith', 'Negan Smith', 1.8542, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/negan_smith-1.8542.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/negan_smith-1.8542.png', NULL, false, NULL, 10000),
('films-walking_dead-rick_grimes', 'Rick Grimes', 1.778, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/rick_grimes-1.778.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/rick_grimes-1.778.png', NULL, false, NULL, 10000),
('films-walking_dead-rosita_espinosa', 'Rosita Espinosa', 1.6, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/rosita_espinosa-1.6.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/rosita_espinosa-1.6.png', NULL, false, NULL, 10000),
('films-walking_dead-sasha_williams', 'Sasha Williams', 1.6383, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/sasha_williams-1.6383.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/sasha_williams-1.6383.png', NULL, false, NULL, 10000),
('films-walking_dead-shane_walsh', 'Shane Walsh', 1.778, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/shane_walsh-1.778.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/shane_walsh-1.778.png', NULL, false, NULL, 10000),
('films-walking_dead-the_governor', 'The Governor', 1.8288, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/the_governor-1.8288.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/the_governor-1.8288.png', NULL, false, NULL, 10000),
('films-walking_dead-tyreese_williams', 'Tyreese Williams', 1.8, ARRAY[0,10,1020], 'image', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/tyreese_williams-1.8.png', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/films/walking_dead/tyreese_williams-1.8.png', NULL, false, NULL, 10000);
